import { useState, useEffect } from 'react';
import api from '../api/axios';
import { Loader2, ExternalLink, Code } from 'lucide-react';

const Community = () => {
    const [projects, setProjects] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchProjects = async () => {
            try {
                const { data } = await api.get('/projects/community');
                setProjects(data);
            } catch (error) {
                console.error("Failed to fetch community projects", error);
            } finally {
                setLoading(false);
            }
        };
        fetchProjects();
    }, []);

    if (loading) {
        return <div className="min-h-screen bg-slate-900 flex items-center justify-center text-white"><Loader2 className="w-8 h-8 animate-spin" /></div>;
    }

    return (
        <div className="min-h-screen bg-slate-900 pt-24 px-4 pb-20">
            <div className="max-w-7xl mx-auto">
                <div className="text-center mb-16">
                    <h1 className="text-4xl font-bold text-white mb-4">Community Showcase</h1>
                    <p className="text-gray-400">Explore websites generated by Buildora AI</p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                    {projects.map((project) => (
                        <div key={project._id} className="bg-slate-800 rounded-2xl border border-white/10 overflow-hidden hover:border-indigo-500/50 transition-all group">
                            {/* Visual Preview Placeholder */}
                            <div className="h-48 bg-slate-900 relative overflow-hidden">
                                <iframe
                                    srcDoc={project.generatedCode}
                                    title={project.title}
                                    className="w-[200%] h-[200%] transform scale-50 origin-top-left pointer-events-none select-none"
                                    tabIndex="-1"
                                />
                                <div className="absolute inset-0 bg-transparent group-hover:bg-slate-900/10 transition-colors"></div>
                            </div>

                            <div className="p-6">
                                <h3 className="text-lg font-semibold text-white mb-2 line-clamp-1">{project.title || "Untitled Project"}</h3>
                                <p className="text-sm text-gray-500 mb-4 line-clamp-2">{project.prompt}</p>

                                <div className="flex items-center justify-between mt-auto">
                                    <span className="text-xs text-indigo-400 font-medium bg-indigo-500/10 px-2 py-1 rounded">
                                        By {project.userId?.name || 'Anonymous'}
                                    </span>
                                    <a
                                        href={`/project/${project._id}`}
                                        className="text-indigo-400 hover:text-indigo-300 text-sm flex items-center gap-1 font-medium"
                                    >
                                        View <ExternalLink className="w-3 h-3" />
                                    </a>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
};

export default Community;
