import { useState, useEffect } from 'react';
import api from '../api/axios';
import { Loader2, ExternalLink, Code, Download } from 'lucide-react';

const Community = () => {
    const [projects, setProjects] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchProjects = async () => {
            try {
                const { data } = await api.get('/projects/community');
                setProjects(data);
            } catch (error) {
                console.error("Failed to fetch community projects", error);
            } finally {
                setLoading(false);
            }
        };
        fetchProjects();
    }, []);

    if (loading) {
        return <div className="min-h-screen bg-slate-900 flex items-center justify-center text-white"><Loader2 className="w-8 h-8 animate-spin" /></div>;
    }

    const handleDownload = (project) => {
        const payload = project.fullSourceCode || project.generatedCode;
        if (!payload) return;
        const blob = new Blob([payload], { type: 'text/html' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${(project.title || 'website').replace(/\s+/g, '_')}.html`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
    };

    const handleOpenInNewTab = (project) => {
        const payload = project.fullSourceCode || project.generatedCode;
        if (!payload) return;
        const newWindow = window.open();
        if (newWindow) {
            newWindow.document.write(payload);
            newWindow.document.close();
        } else {
            // Alternatively we can just use console or alert if toast isn't imported, but toast is better.
            // Wait, we need to import toast if it's not here. Let me check if toast is imported.
            // Hmm, I will just use standard alert to be safe if toast isn't in Community.jsx, or I can import it.
            // The file doesn't seem to import toast currently based on previous views. I'll use standard alert to prevent errors.
            alert("Please allow popups to view the site in a new tab.");
        }
    };

    return (
        <div className="min-h-screen bg-slate-900 pt-24 px-4 pb-20">
            <div className="max-w-7xl mx-auto">
                <div className="text-center mb-16">
                    <h1 className="text-4xl font-bold text-white mb-4">Community Showcase</h1>
                    <p className="text-gray-400">Explore websites generated by Buildora AI</p>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                    {projects.map((project) => (
                        <div key={project._id} className="bg-slate-800 rounded-2xl border border-white/10 overflow-hidden hover:border-indigo-500/50 transition-all group">
                            {/* Visual Preview Placeholder */}
                            <div className="h-48 bg-slate-900 relative overflow-hidden">
                                <iframe
                                    srcDoc={project.generatedCode}
                                    title={project.title}
                                    className="w-[200%] h-[200%] transform scale-50 origin-top-left pointer-events-none select-none"
                                    tabIndex="-1"
                                />
                                <div className="absolute inset-0 bg-transparent group-hover:bg-slate-900/10 transition-colors"></div>
                            </div>

                            <div className="p-6">
                                <h3 className="text-lg font-semibold text-white mb-2 line-clamp-1">{project.title || "Untitled Project"}</h3>
                                <p className="text-sm text-gray-500 mb-4 line-clamp-2">{project.prompt}</p>

                                <div className="flex items-center justify-between mt-auto">
                                    <span className="text-xs text-indigo-400 font-medium bg-indigo-500/10 px-2 py-1 rounded">
                                        By {project.userId?.name || 'Anonymous'}
                                    </span>
                                    <div className="flex items-center gap-2">
                                        <button
                                            onClick={() => handleOpenInNewTab(project)}
                                            className="bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-1.5 rounded-lg text-xs font-bold transition-colors flex items-center justify-center gap-2"
                                        >
                                            <ExternalLink className="w-3 h-3" /> View
                                        </button>
                                        <button
                                            onClick={() => handleDownload(project)}
                                            className="p-1.5 text-gray-400 hover:text-white hover:bg-white/10 rounded-lg transition-colors"
                                            title="Download HTML"
                                        >
                                            <Download className="w-4 h-4" />
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
};

export default Community;
